import 'package:flutter/material.dart';

const fallbackSymbolIcon = Icons.circle_outlined;

// A category stores one of these names as free text, so a name this build does
// not know still has to render.
const _chromeIcons = <String, IconData>{
  'menu_book': Icons.menu_book,
  'pie_chart_outline': Icons.pie_chart_outline,
  'wallet': Icons.account_balance_wallet_outlined,
  'settings_outlined': Icons.settings_outlined,
  'add': Icons.add,
  'edit': Icons.edit_outlined,
  'delete': Icons.delete_outline,
  'undo': Icons.undo,
  'close': Icons.close,
  'check': Icons.check,
  'chevron_left': Icons.chevron_left,
  'chevron_right': Icons.chevron_right,
  'expand_more': Icons.expand_more,
  'repeat': Icons.repeat,
  'change_circle': Icons.change_circle,
  'inbox': Icons.inbox_outlined,
  'payments_outlined': Icons.payments_outlined,
  'label_outline': Icons.label_outline,
  'remove_circle': Icons.remove_circle,
  'add_circle': Icons.add_circle_outline,
  'bar_chart': Icons.bar_chart,
  'swap_horiz': Icons.swap_horiz,
  'help_outline': Icons.help_outline,
  'radio_button_checked': Icons.radio_button_checked,
};

/// Icon names grouped by section, in the order the picker shows them.
const categoryIconSections = <String, List<String>>{
  'Food & Drink': [
    'shopping_cart',
    'restaurant',
    'local_cafe',
    'wine_bar',
    'emoji_food_beverage',
    'cake',
    'eco',
    'takeout_dining',
    'local_movies',
    'set_meal',
  ],
  'Transport': [
    'directions_car',
    'directions_bus',
    'tram',
    'flight',
    'directions_bike',
    'local_gas_station',
    'directions_boat',
    'two_wheeler',
    'directions_walk',
    'local_parking',
  ],
  'Home & Bills': [
    'home',
    'king_bed',
    'weekend',
    'bolt',
    'water_drop',
    'local_fire_department',
    'wifi',
    'phone',
    'delete_filled',
    'handyman',
  ],
  'Shopping': [
    'shopping_bag',
    'card_giftcard',
    'checkroom',
    'hiking',
    'work',
    'auto_awesome',
    'label',
    'credit_card',
    'redeem',
    'inventory_2',
  ],
  'Health': [
    'medical_services',
    'medication',
    'favorite',
    'monitor_heart',
    'healing',
    'directions_run',
    'fitness_center',
    'visibility',
    'sentiment_satisfied',
    'psychology',
  ],
  'Leisure': [
    'movie',
    'music_note',
    'sports_esports',
    'book',
    'confirmation_number',
    'theater_comedy',
    'photo_camera',
    'beach_access',
    'brush',
    'queue_music',
  ],
  'Work & Education': [
    'business_center',
    'school',
    'laptop',
    'architecture',
    'apartment',
    'print',
    'newspaper',
    'people',
    'calendar_today',
    'email',
  ],
  'Money': [
    'attach_money',
    'payments',
    'trending_up',
    'pie_chart',
    'account_balance',
    'percent',
    'account_balance_wallet',
    'currency_bitcoin',
    'thumb_up',
    'savings',
  ],
  'Other': [
    'star',
    'flag',
    'pets',
    'energy_savings_leaf',
    'public',
    'settings',
    'notifications',
    'lightbulb',
    'category',
    'more_horiz',
  ],
};

const _categoryIcons = <String, IconData>{
  'shopping_cart': Icons.shopping_cart_outlined,
  'restaurant': Icons.restaurant,
  'local_cafe': Icons.local_cafe,
  'wine_bar': Icons.wine_bar,
  'emoji_food_beverage': Icons.emoji_food_beverage,
  'cake': Icons.cake,
  'eco': Icons.eco,
  'takeout_dining': Icons.takeout_dining,
  'local_movies': Icons.local_movies,
  'set_meal': Icons.set_meal,

  'directions_car': Icons.directions_car,
  'directions_bus': Icons.directions_bus,
  'tram': Icons.tram,
  'flight': Icons.flight,
  'directions_bike': Icons.directions_bike,
  'local_gas_station': Icons.local_gas_station,
  'directions_boat': Icons.directions_boat,
  'two_wheeler': Icons.two_wheeler,
  'directions_walk': Icons.directions_walk,
  'local_parking': Icons.local_parking,

  'home': Icons.home,
  'king_bed': Icons.king_bed,
  'weekend': Icons.weekend,
  'bolt': Icons.bolt,
  'water_drop': Icons.water_drop,
  'local_fire_department': Icons.local_fire_department,
  'wifi': Icons.wifi,
  'phone': Icons.phone,
  'delete_filled': Icons.delete,
  'handyman': Icons.handyman,

  'shopping_bag': Icons.shopping_bag,
  'card_giftcard': Icons.card_giftcard,
  'checkroom': Icons.checkroom,
  'hiking': Icons.hiking,
  'work': Icons.work_outline,
  'auto_awesome': Icons.auto_awesome,
  'label': Icons.label,
  'credit_card': Icons.credit_card,
  'redeem': Icons.redeem,
  'inventory_2': Icons.inventory_2,

  'medical_services': Icons.medical_services,
  'medication': Icons.medication,
  'favorite': Icons.favorite,
  'monitor_heart': Icons.monitor_heart,
  'healing': Icons.healing,
  'directions_run': Icons.directions_run,
  'fitness_center': Icons.fitness_center,
  'visibility': Icons.visibility,
  'sentiment_satisfied': Icons.sentiment_satisfied,
  'psychology': Icons.psychology,

  'movie': Icons.movie,
  'music_note': Icons.music_note,
  'sports_esports': Icons.sports_esports,
  'book': Icons.book,
  'confirmation_number': Icons.confirmation_number,
  'theater_comedy': Icons.theater_comedy,
  'photo_camera': Icons.photo_camera,
  'beach_access': Icons.beach_access,
  'brush': Icons.brush,
  'queue_music': Icons.queue_music,

  'business_center': Icons.business_center,
  'school': Icons.school,
  'laptop': Icons.laptop,
  'architecture': Icons.architecture,
  'apartment': Icons.apartment,
  'print': Icons.print,
  'newspaper': Icons.newspaper,
  'people': Icons.people,
  'calendar_today': Icons.calendar_today,
  'email': Icons.email,

  'attach_money': Icons.attach_money,
  'payments': Icons.payments,
  'trending_up': Icons.trending_up,
  'pie_chart': Icons.pie_chart,
  'account_balance': Icons.account_balance,
  'percent': Icons.percent,
  'account_balance_wallet': Icons.account_balance_wallet,
  'currency_bitcoin': Icons.currency_bitcoin,
  'thumb_up': Icons.thumb_up,
  'savings': Icons.savings,

  'star': Icons.star,
  'flag': Icons.flag,
  'pets': Icons.pets,
  'energy_savings_leaf': Icons.energy_savings_leaf,
  'public': Icons.public,
  'settings': Icons.settings,
  'notifications': Icons.notifications,
  'lightbulb': Icons.lightbulb,
  'category': Icons.category,
  'more_horiz': Icons.more_horiz,
};

/// Every name the picker offers, in section order.
List<String> get categoryIconNames => [
  for (final section in categoryIconSections.values) ...section,
];

IconData symbolIcon(String name) =>
    _categoryIcons[name] ?? _chromeIcons[name] ?? fallbackSymbolIcon;
